apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: agent-analyze-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-analyze
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20